POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1",
    "name": "NameTest"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1"
}
