POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "uid": "",
    "email": "",
    "password": "",
    "name": ""
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1"
}

###
GET http://localhost:3000/api/firebase-auth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1NzA4MWNhOWNiYjM3YzIzNDk4ZGQzOTQzYmYzNzFhMDU4ODNkMjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmxhc2hjYXJkLWlvdCIsImF1ZCI6ImZsYXNoY2FyZC1pb3QiLCJhdXRoX3RpbWUiOjE3NDQ5Njk0NTIsInVzZXJfaWQiOiJ5QTFxRWlCazM2U0Y2d2NYMDJmRUg5ZktWdjgzIiwic3ViIjoieUExcUVpQmszNlNGNndjWDAyZkVIOWZLVnY4MyIsImlhdCI6MTc0NDk2OTQ1MiwiZXhwIjoxNzQ0OTczMDUyLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0MkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.WgiAblIkgbRXOTaz4v9CGrhIJC7h5fkrM3g5S3M4hSZhOwGasCa0d86WGtCQjjkr5gpsBxJUurZyWAu8jopV-IX0M5Jvw4r144_bKV5sTROqu1Oa1qLPOA0__ut7801YeQSZoWU7DRnBbrRDm7Gqpy_Yjz1aIwDCdZaDqYl-2j7zwJMk054BNuwrP7uNy_ESoEM2_YXyGDi4KAgpoT451dXvD8Kqp5susQhsTR_ZfVMsOMf6XzKm48mnmt45dZ-oC3JwvXS6HfzVXk2s-Y4nUbZmruHMYrUB6ag4Vk4GDbDs5xICEO0BGXNrT2EJZBL-kJPJrj9pRA6OjqBH35nApg
